spring.application.name=IdentityService

server.port=8086

spring.datasource.url=jdbc:h2:mem:usersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.main.web-application-type=reactive
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}

# Define the location for log files
logging.file.name=C://Users/somyagupta01/myProjects/microservices/logs/zion.log


#For actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always